# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20160305_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='pump_1_pwm',
            field=models.FloatField(default=0, verbose_name=b'Pump 1 PWM'),
        ),
        migrations.AddField(
            model_name='phase',
            name='pump_2_pwm',
            field=models.FloatField(default=0, verbose_name=b'Pump 2 PWM'),
        ),
    ]
