# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20160317_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='pump_1_actuator_id',
            field=models.IntegerField(null=True, verbose_name=b'Pump 1 Actuator'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='pump_2_actuator_id',
            field=models.IntegerField(null=True, verbose_name=b'Pump 2 Actuator'),
        ),
    ]
