# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_brewpi_spark_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewpi',
            name='system_version',
            field=models.CharField(default=b'0.0', max_length=10, verbose_name=b'System Version'),
        ),
    ]
