# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_brewpi_system_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='cooling_off_period',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='cooling_on_period',
        ),
        migrations.AddField(
            model_name='phase',
            name='cooling_off_time',
            field=models.IntegerField(default=300000, verbose_name=b'Cooling Off Time'),
        ),
        migrations.AddField(
            model_name='phase',
            name='cooling_on_time',
            field=models.IntegerField(default=180000, verbose_name=b'Cooling On Time'),
        ),
        migrations.AddField(
            model_name='phase',
            name='cooling_period',
            field=models.IntegerField(default=1200000, verbose_name=b'Cooling Period'),
        ),
    ]
